### ISSUE TITLE
Possibly adding a Video about git revert and git reset

### ISSUE THREAD

**Issue by Abbott-2010-69** [CodingTrain/Rainbow-Poem#626]
Hi @DanielShiffman 

Great work with the series of videos on git and github. As someone who has just started using git I was wondering if you could add a video to this series about using git revert to go back to an earlier commit in a master branch. Also when is it appropriate to use git reset.

Thank you for all your hard work. You are an amazing coding teacher. Keep up the good work.

**Comment by rekaut** [comment]
Hi @danielshiffman

Great work with the series of videos on git and github. As someone who has just started using git I was wondering if you could add a video to this series about using git revert to go back to an earlier commit in a master branch. Also when is it appropriate to use git reset.

Thank you for all your hard work. You are an amazing coding teacher. Keep up the good work.

**Comment by akraus53** [comment]
This is a good idea! Dan sadly can't keep track of this repo anymore, but you can add this to the rainbow topics here: https://github.com/CodingTrain/Rainbow-Topics

**Comment by Abbott-2010-69** [comment]
Hi @akraus53 

Thanks for the reply totally forgot about this. I did include a suggestion for this topic in that repo. See 
 [https://github.com/CodingTrain/Rainbow-Topics/issues/934](url)

I guess Dan is really busy with tensorflow at the moment. Anyway, as an aside may I ask how you became a collaborator ?

**Comment by akraus53** [comment]
Hi @Abbott-2010-69,
I think making a git tutorial is a one-take video for dan, it shouldn't take more than 5mins in the beginning of a stream, also he wants to do some other content anyway, sadly from what I've seen the Tensorflow videos aren't being watched a lot. 

I became a collaborator because I was chatting with shiffman on slack about this repo and that he sadly can't keep up with the merging, so I suggested I help out a bit. I assume he recognized my name from before (and therefore trusted me??) and gave me merge rights for this repo. So if you want to collaborate as well, my best tip is to get active in the community!

**Comment by akraus53** [comment]
btw i think you messed up the markdown for the link to the issue 😆 It's [text] (url), not [url] (text)

**Comment by shiffman** [comment]
Just an FYI that I am reading these comments, thank you @akraus53 for all of this help!

**Comment by Abbott-2010-69** [comment]
😳 Wow, I am so star-struck. I can't believe Daniel Shiffman really replied on a topic I started. I have to call my mom.
